### ISSUE TITLE
displaying hashmaps? 

### ISSUE THREAD

**Issue by ecoquant** [vgherard/r2r#5]
Because the print method is intercepted by r2r hashmap objects, when it is ticked in RStudio, all that is displayed is "An r2r hashmap."  Is there some way of shutting this off? Once I've built a hashmap, I'd like to be able to see it.  

Of course, I can write a custom print method, but, generally speaking, R tools have a lot of capability there.

It's a little annoying, but, if H is an r2r hashmap, I can do:

z<- values(H)
names(z)<- keys(H)
print(z)

Thanks.

**Comment by vgherard** [comment]
Hi @ecoquant , thanks for your comment. 

I understand the problem. The issue with a `print`, or maybe `format`, method of the kind you suggest is that, while you seem to be employing string keys in your particular use case, `r2r` hashmap keys are in principle allowed to be any R object. Hence, the `names(z) <- keys(H)` step you suggest would not work for the general case.

On the other hand, I'm positve to trying something like:

```r
format.r2r_hashmap <- function(H) {
  z <- values(H)
  names(z) <- as.character(keys(H))
  #  ... Fail gracefully if keys(H) is not coercible to character in a meaningful way ...
  print(z)
}
```

Here I would need to define carefully what is meant by "meaningful way", since keys could by themselves be `length>1` 
 character vectors, complicating the story a little bit.

What do you think?

**Comment by vgherard** [comment]
Another simple fix you could try yourself would be to define a custom S3 class which inherits from `r2r_hashmap` (of class `c("my_hashmap", class(r2r::hashmap()))`, say) and define its print method in the way you like. If you need help with this I would be glad to offer some :-)

**Comment by ecoquant** [comment]
Thanks for considering the suggestion, and I wish you well.

For application in hand at present, I've moved to using the fastmap package
instead of r2r, since I don't need arb objects as keys, and can do strings.

 - Jan

**Comment by vgherard** [comment]
Thanks for pointing out, I didn't know about this package - looks very performant.
